### ISSUE TITLE
Anlegen der Layer im Geoserver

### ISSUE THREAD

**Issue by root676** [tuwien-geoweb/g07-2014#11]

**Comment by iemg** [comment]
Testweise zwei Layer angelegt (g07_2014_p_bezirksgrenzen & g07_2014_p_bezirksgrenzen_pop)

**Comment by root676** [comment]
Restliche Layer aus der Datenbank wurden im Geoserver angelegt. Das begrenzende Rechteck wurde bei allen Layern analog zur Übung aus den Daten berechnet. --> Nachträglich auch für die Layer g07_2014_p_bezirksgrenzen & g07_2014_p_bezirksgrenzen_pop übernommen. Folgende Layer stehen zur Auswahl:
![layerauswahl_geoserver](https://cloud.githubusercontent.com/assets/9716552/5561222/fdb15eaa-8dc9-11e4-8288-57b9b3266368.PNG)
