### ISSUE TITLE
Verknüpfung der Layer mit der HTML-Oberfläche

### ISSUE THREAD

**Issue by root676** [tuwien-geoweb/g07-2014#13]

**Comment by iemg** [comment]
Erster Test: Bezirksgrenzen als eigene var definiert, und verknüpft mit HTML-Oberfläche: nun ein- und ausschaltbar.

**Comment by root676** [comment]
Die Karte müsste noch ein bisschen besser in die HTML Oberfläche eingepasst werden. Ich werde mir das zugehörige Bootstrap mal anschauen...

**Comment by iemg** [comment]
So weit nur working prototype. Bessere Implementierung inkl. Darstellung folgt.

Desweiteren:
- Ein- und Ausschaltbarkeit von Layern ev. über andere Methode (http://geo.dianacht.de/tests/extlayer2.html), muss ich mir noch anschauen.
