### ISSUE TITLE
Benutzergesteuertes Hinzufügen von Wohnstandorten in die Geodatenbank

### ISSUE THREAD

**Issue by root676** [tuwien-geoweb/g07-2014#15]

**Comment by root676** [comment]
Der Wohnstandort des Nutzers wird über die Nominatim Funktion hinzugefügt. Der dazu notwendige Code wird in Javascript implementiert und in die Sqlite Tabelle wohnstandorte eingefügt (ID, Adresse, geom).

**Comment by root676** [comment]
Hallo @ahocevar !
Wir haben ein kleines Problem beim schreiben von Punktdaten in die Geodatenbank. Das Problem ähnelt dem der Gruppe 5, als sie die geolocation Punkte des Feedback-Formulars nicht in die Tabelle Feedback schreiben konnten. 
In unserem Fall wollen wir Wohnstandorte in die Datenbank (Tabelle "wohnstandorte" ist bereits angelegt) hinzufügen. Dies soll über den Viewmittelpunkt des von Nominatim übermittelten Bildausschnittes geschehen. Die Koordinaten werden laut Abfrage in JS-Konsole richtig projiziert. Als zweites Attribut soll der Nominatim Suchstring in die Datenbank gespeichert werden. Die Funktion übermittelt bereits Daten an den Geoserver, dieser antwortet jedoch mit folgender Meldung:
![feature_insert_error](https://cloud.githubusercontent.com/assets/9716552/5635626/04c2aedc-95eb-11e4-813f-c8a390104356.PNG)
FeatureNS und FeatureType sind mit dem Datenspeicher/Layer im Geoserver abgestimmt und müssen stimmen. Ich habe bereits versucht die Datenbank umzubenennen. Dies führt allerdings auch zu keiner Lösung. Könntest du uns helfen?
Die Seite ist unter folgender URL abrufbar: http://tuwien-geoweb.github.io/g07-2014/wohnstandortanalyse/map.html

Vielen Dank!

lg @root676

**Comment by root676** [comment]
Das Einfügen der Wohnstandorte funktioniert nach einigem Probieren doch.

**Comment by iemg** [comment]
Funktioniert irgendwie doch nicht?

**Comment by ahocevar** [comment]
Ich habe eure Datenbank am Server von `g07_geowebdb_enh.sqlite` auf `g07_geowebdb.enha.sqlite` umbenannt, und den Namen auch in der Datenspeicher-Konfiguration im GeoServer geändert. Dadurch wurde das Problem behoben.

Falls wieder jemand einen "Some Disk I/O Error Occurred" Fehler bekommt, ist das die Lösung.

**Comment by root676** [comment]
Danke!
