### ISSUE TITLE
Benachrichtigung der Lehrveranstaltungsleiter

### ISSUE THREAD

**Issue by root676** [tuwien-geoweb/g07-2014#20]
Hallo @ahocevar , @jbroetha !
Die grundlegenden Funktionen und Vorgangsweise zur Erstellung des Endprojektes wurden in Form von Milestones und darunter aufgegliederten Issues durch die Gruppe publiziert. Eine genauere Beschreibung des Projektes und der zu verwendeten Datenschichten sind in den Beschreibungen der Milestones und den zugeordneten Issues zu finden.
Bitte um Rückmeldung ob die Vorgehensweise in Ordnung ist. 

lg @root676, @iemg , @KerstinRamona

**Comment by ahocevar** [comment]
Sieht aus meiner Sicht gut aus, ihr könnt also mit der Umsetzung beginnen.
