### ISSUE TITLE
Adresssuche: OGD Wien Adressservice oder Nominatim?

### ISSUE THREAD

**Issue by iemg** [tuwien-geoweb/g07-2014#21]
OSM Nominatim: bereits implementiert.

OGD Wien Adressservice: erster Versuch fehlgeschlagen, ev. nur über Umwege einbaubar? (vgl. http://www.open3.at/projekte/ogd-wien-adressservice-unterstuetzung-fuer-geocoder-php-bibliothek, andererseits sollte ja nur geoJSON sein, ev. iwo Denkfehler)

**Comment by root676** [comment]
OGD Adresssuche sollte aus Zeitgründen in AP 5 Zusatzfunktionen übernommen werden. Nominatim sollte fürs erste ausreichen.
