### ISSUE TITLE
Basemap.at WMTS

### ISSUE THREAD

**Issue by root676** [tuwien-geoweb/g07-2014#23]
Ich habe auf Openlayers ein Beispiel zur Einbindung der Basemap.at gefunden. Es ist ein Beispiel zur Einbindung der hochauflösenden Kartenversion.

http://openlayers.org/en/v3.0.0/examples/wmts-hidpi.html

**Comment by iemg** [comment]
Optional, wenn zu viel Zeit bleibt: Basiskarte auswählbar über Dropdown?

**Comment by root676** [comment]
Gute Idee! Ich werde die Basemap.at mal als Grundkarte in der Wohnstandortanalyse einrichten. Ich werde das dropdown Menü in das optionale Arbeitspaket reinschreiben.

**Comment by iemg** [comment]
Danke!

Basemap funktioniert jetzt, attribution fehlt nun aber…

**Comment by root676** [comment]
Ich werde mich darum kümmern. Wir sollten die gesamte Homepage auf github Pushen, damit wir keine Konflikte produzieren.

**Comment by iemg** [comment]
Ich arbeite eh nur in der Nacht :smiley: 

Aber ja, kannst du gerne machen, wenn du magst :wink: ! Würden wir dann bis zum ersten Release einfach auf github arbeiten und dann erst auf den ifip-server wechseln? (wird halt mit manchen Pfaden auf der HP nicht funktionieren)

**Comment by root676** [comment]
:smiley: 
Ich einen Prototypen können wir ja mal erstellen. Skripte werden in Github geschrieben, in die Homepage integrieren wir den Sourcecode erst beim Release am IFIP Server. Meld mich wenns so weit ist. :wink:

**Comment by iemg** [comment]
Man könnte auch die Karte in ein .js auslagern und das auf der Homepage zum Testen – temporär – auf github verweisen.

**Comment by KerstinRamona** [comment]
Ich werd mir das mal anschauen.

**Comment by KerstinRamona** [comment]
So! Nach einigen Pushversuchen steht der Prototyp jetzt auf Github im Branch gh-pages, wohnstandortanalyse/map.html & wohnstandortanalyse.js
Ich hab mir erlaubt den Quellcode etwas aufzuräumen/ zu strukturieren und habe den großteil mit Kommentaren versehen. Bitte haltet euch an die nun geschaffene Ordnung (einrücken vom Quellcode mit zwei Leerzeichen, sinnvolle Kommentare und Funktions- bzw. Buttonbezeichnungen)!!! Wenn wir fertig sind und den Prototypen auf die HP migrieren, dann müssen nur mehr die Bootstrap Frameworks und Openlayers im Head neu verknüpft werden. 

Der Prototyp kann über folgenden Link abgerufen werden:

http://tuwien-geoweb.github.io/g07-2014/wohnstandortanalyse/map.html

Leider musste ich den Bezirkslayer auskommentieren, da iwer den Geoserver schon wieder ruiniert hat... :frowning:

**Comment by root676** [comment]
Cool! Vielen Dank fürs Pushen!!
Ich werde die LVA-Leiter bitten, den Geoserver zu rebooten.

**Comment by jbroetha** [comment]
Liebe Kollegen,

das Problem wurde bereits an den Techniker weitergeleitet
(er ist derzeit auf Urlaub – ich hoffe, es klappt kurzfristig – jede Nacht wird der Geoserver automatisch neu gestartet)

LG
J. Bröthaler

Von: Clemens Raffler [mailto:notifications@github.com]
Gesendet: Montag, 29. Dezember 2014 15:24
An: tuwien-geoweb/g07-2014
Betreff: Re: [g07-2014] Basemap.at WMTS (#23)

Cool! Vielen Dank fürs Pushen!!
Ich werde die LVA-Leiter bitten, den Geoserver zu rebooten.

**Comment by root676** [comment]
@jbroetha ah, das ist super! Vielen Dank!
