### ISSUE TITLE
Einrücken

### ISSUE THREAD

**Issue by iemg** [tuwien-geoweb/g07-2014#26]
Sry, aber irgendeins der Programme vermurkst es immer (diesmal wohl github). Ich werd mich trotzdem bemühen, aber ich glaub, wir sollten unsere Energie nicht darauf verschwenden, die Editoren machen eh was sie wollen.

![bildschirmfoto 2014-12-29 um 17 45 19](https://cloud.githubusercontent.com/assets/9716564/5570485/86b96594-8f82-11e4-841b-2d04fcb88693.png) ![bildschirmfoto 2014-12-29 um 17 44 20](https://cloud.githubusercontent.com/assets/9716564/5570486/86dff038-8f82-11e4-8863-3bb1f96fa577.png)

**Comment by root676** [comment]
Der code soll ja nur nicht auschauen wie Sau... ;-)
