### ISSUE TITLE
Vektor-Layer funktionsunfähig

### ISSUE THREAD

**Issue by iemg** [tuwien-geoweb/g07-2014#27]
Nun endlich alle Punkte-Layer in den working prototype implementiert: http://tuwien-geoweb.github.io/g07-2014/wohnstandortanalyse/map.html

Geht allerdings nur als WMS, als Vektorlayer unmöglich.

```
    var lay_p_tempo30 = new ol.layer.Vector({
                source: new ol.source.Vector({
                  url: 'http://student.ifip.tuwien.ac.at/geoserver/wfs',
                  params: {VERSION: '1.0.0', typeName: 'g07_2014:g07_2014_p_tempo30zonen'},
                }),
    style: new ol.style.Style({
  'pointRadius': 10
            })
              });
```

als auch

```
var lay_p_fahrrad_vec = new ol.layer.Vector({
              source: new ol.source.GeoJSON({
                  url: 'http://student.ifip.tuwien.ac.at/geoserver/g07_2014/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=g07_2014:g07_2014_p_carsharing_standorte&maxFeatures=50&outputFormat=json'
                }),
    style: new ol.style.Style({
  'pointRadius': 10
            })
            });
```

funktionieren nicht, obwohl die WFS-Koordinaten in den Browser geladen werden.

Habe mich dabei an verschiedenen Beispielen orientiert, u.a. https://github.com/openlayers/ol3/wiki/Minimal-Vector-API und http://student.ifip.tuwien.ac.at/geoweb/2013/g03/app/ws_suche/applikation.html

Soll man die (und alle übrigens) als WMS einbinden oder findet sich ein schlauer Kopf?

**Comment by root676** [comment]
Ich werds mir mal anschauen.

**Comment by root676** [comment]
Ja, wenn man einen POLYGON-Layer mit einem PUNKT Stil versieht, dann kanns ja nicht funktionieren... :neutral_face:

**Comment by iemg** [comment]
Das waren nur zusammenkopierte Code-Schnippsel, es hat auch ohne Style bzw. mit Polygon-Style nicht funktioniert, danke auf jeden fall (wie hast du das gemacht?).

Die Punkt-Vektor-Layer (zweites Code-Bsp) funktionieren bei mir übrigens (auch mit `projection: 'EPSG:3857'`) weiterhin nicht.

**Comment by root676** [comment]
Welches Beispiel/Layer meinst du genau? Der Parameter projection: 'EPSG:3857' ist im Prinzip auch nur ein zusätzlicher Input, der nicht unbedingt gebraucht wird.

**Comment by iemg** [comment]
Ist jetzt nicht mehr im file drin, aber das hier:

```
var lay_p_fahrrad_vec = new ol.layer.Vector({
              source: new ol.source.GeoJSON({
                  url: 'http://student.ifip.tuwien.ac.at/geoserver/g07_2014/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=g07_2014:g07_2014_p_carsharing_standorte&maxFeatures=50&outputFormat=json'
                }),
    style: new ol.style.Style({
  'pointRadius': 10
            })
            });
```

funktioniert bsp nicht (nicht wegen der Benennung schlagen, das war nur zu Testzwecken ;))

**Comment by root676** [comment]
Naja die Zeile 'pointRadius': 10 sagt ja nur wie groß der Punkt sein soll. Aber Farben nehm ich an brauchst auch. Ansonsten kann ich keinen Fehler entdecken.

**Comment by iemg** [comment]
Ich habs mit verschiedenen Beispielstyles probiert, hat aber alles nicht funktioniert… :disappointed:

**Comment by root676** [comment]
Aber, brauchen wir noch layer in der Applikation? Der Rest wird doch eh schon über WMS mit SLD dargestellt.

**Comment by iemg** [comment]
Ja, das stimmt schon.

Trotzdem ärgerlich, dass es nicht funktioniert.
