### ISSUE TITLE
PtDistWithin funktioniert im Geoserver nicht

### ISSUE THREAD

**Issue by KerstinRamona** [tuwien-geoweb/g07-2014#29]
Ich habe gerade versucht die Query für die Wohnstandortanalyse als SQL-View in einen neuen Layer zu speichern. Dabei kam jedoch folgende Fehlermeldung:
[SQLITE_ERROR] SQL error or missing database (no such function: PtDistWithin)
Anscheinend erkennt der Server die Funktion nicht als valide an... Ich glaube das müssen wir umschreiben oder lassen...

**Comment by KerstinRamona** [comment]
Ooooookeyyy.... Anscheinend hat die neue SQL Abfrage den Geoserver ruiniert... Er ist nicht erreichbar.

**Comment by root676** [comment]
@ahocevar könnte man bitte den Geoserver neu starten, damit das Weiterarbeiten möglich ist? Danke!

**Comment by ahocevar** [comment]
Bitte um Neustart habe ich weitergeleitet, ich hoffe ich bekomme gleich Antwort.

**Comment by root676** [comment]
@ahocevar 
Danke! 
Könntest du dir bei Gelegenheit diese SQL Abfrage ansehen:
https://github.com/tuwien-geoweb/g07-2014/blob/gh-pages/wohnstandortanalyse/getfeatureinfo_wohnstandorte.sql
Ich möchte sie nur nicht wieder in den Geoserver reinladen und ihn damit gleich wieder ruinieren. 
Unsere Absicht ist mithilfe dieser Abfrage mittels SQL-View einen Layer zu erstellen, welcher anschließend per WMSGetFeatureInfo abgefragt werden kann. Ist das Skript zu kompliziert für die Datenbank oder hakt es woanders? Danke!

lg @root676

**Comment by ahocevar** [comment]
PtDistWithin ist in der von GeoServer verwendeten SQLite Version noch nicht verfügbar. Siehe https://www.gaia-gis.it/spatialite-2.3.1/spatialite-sql-2.3.1.html.

**Comment by ahocevar** [comment]
GeoServer ist neu gestartet.

**Comment by root676** [comment]
@ahocevar Danke!

**Comment by root676** [comment]
Layer wohnstandorte_join_zbez wurde konnte mit stark vereinfachter SQL-Abfrage publiziert und eingebunden werden. 
https://github.com/tuwien-geoweb/g07-2014/blob/gh-pages/wohnstandortanalyse/getfeatureinfo_wohnstandorte_join_zbez.sql
