### ISSUE TITLE
Formulardaten können nicht über Geoserver an Datenbank übermittelt werden.

### ISSUE THREAD

**Issue by root676** [tuwien-geoweb/g07-2014#3]
Hallo @ahocevar !
Das Einfügen des Feedback-Formularinhaltes (inkl. Geokoordinaten) über den Geoserver in die SQLite Datenbank funktioniert leider nicht. Ich erhalte vom Geoserver eine Fehlermeldung, deren Zustandekommen ich mir nicht erklären kann. Folgende Schritte habe ich durchgeführt um den Fehler zu umgehen:
1) Einstellungen des Geoservers überprüft (Datenspeicher, URI, Namen der Layer, ...).
2) Speichern des Javascripts für Kontaktaufnahme mit Server auf dem lokalen Webspace.
3) Überprüfen des Include Paths der Datenbank am Geoserver (DB liegt in Unterverzeichnis).
4) Setzen aller Lese- und Schreibrechte in der Datenbank.
5) Geolocating Anfrage im Browser wurde jedes mal bestätigt. 
Das Formular ist unter folgendem Link abrufbar:

http://student.ifip.tuwien.ac.at/geoweb/2014/g07/homepage/content/feedback.php

Eine Karte wurde bereits eingefügt, die Abfrage des GeoJSON zum entsprechenden Layer der Gruppe 07 wurde ebenfalls bereits eingebunden. Vielleicht wäre es möglich das Problem morgen in der Übung zu erörtern. Vielen Dank!

lg Clemens

**Comment by ahocevar** [comment]
Es war nur eine Kleinigkeit:

> 4) Setzen aller Lese- und Schreibrechte in der Datenbank.

Es müssen nicht nur die Schreibrechte auf der Datenbank-Datei selbst, sondern auch am Verzeichnis, in dem sich die Datenbank befindet (also bei euch htdocs/g07/content). Ich hab mir erlaubt, diese Rechte zu setzen. Danach muss man noch im GeoServer auf die Layer-Konfiguration gehen, und ganz unten "Reload feature type" und danach "Save" klicken. Hab ich mir ebenfalls erlaubt, das zu erledigen.

Habe das Formular getestet, und es funktioniert.
