### ISSUE TITLE
Transfer von GitHub auf Homepage

### ISSUE THREAD

**Issue by root676** [tuwien-geoweb/g07-2014#30]

**Comment by root676** [comment]
@iemg Applikation ist fertig und kann auf die Homepage übertragen werden. Kannst du das bitte übernehmen?

**Comment by iemg** [comment]
Ja, mach ich dann in den nächsten Tagen.

**Comment by iemg** [comment]
Erster Schritt getan: http://student.ifip.tuwien.ac.at/geoweb/2014/g07/homepage/content/wohnstandortanalyse.php

Es folgen noch kosmetische Feinheiten.

**Comment by root676** [comment]
Also bei mir hats wieder funktioniert, das Feedback Formular. :wink:

**Comment by iemg** [comment]
Ich hab keine E-Mail bekommen, und nichts in der Datenbank gefunden

Hast du es auf der Homepage oder im Github probiert? Auf der Homepage krieg ich das:

![bildschirmfoto 2015-01-14 um 12 54 49](https://cloud.githubusercontent.com/assets/9716564/5738455/a015efa0-9bec-11e4-9535-ff18f801dbb4.png)

**Comment by root676** [comment]
Das sollte auch passen, was du da siehst. Er schreibt dir mit dem XML 
nur hin, dass er Daten bekommen hat und sie per WFS in die Datenbank 
eingefügt hat. Ich habs auf dem student webspace probiert. Wenn diese 
Nachricht kommt sollte es eigentlich ok sein (siehe 
<totalInserted>1</totalInserted>).

lg Clemens
Am 14.01.2015 um 12:56 schrieb Isaak:

> Ich hab keine E-Mail bekommen, und nichts in der Datenbank gefunden
> 
> Hast du es auf der Homepage oder im Github probiert? Auf der Homepage 
> krieg ich das:
> 
> bildschirmfoto 2015-01-14 um 12 54 49 
> https://cloud.githubusercontent.com/assets/9716564/5738455/a015efa0-9bec-11e4-9535-ff18f801dbb4.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/tuwien-geoweb/g07-2014/issues/30#issuecomment-69906179.

## 

Clemens Raffler Bakk. Techn.
Raumplanung und Raumordnung
clemens.raffler@gmx.at

**Comment by iemg** [comment]
Ah, dürft falsch nachgeschaut haben. Ok, danke.
