### ISSUE TITLE
Änderung der Layer-Reihenfolge

### ISSUE THREAD

**Issue by root676** [tuwien-geoweb/g07-2014#37]
Wohnstandorte WMS sollte als oberstes angezeigt werden.

**Comment by iemg** [comment]
sollte damit funktionieren: http://openlayers.org/en/v3.1.1/apidoc/ol.style.Style.html?unstable=true#setZIndex

**Comment by iemg** [comment]
Ich kriegs leider nicht hin :disappointed:

**Comment by root676** [comment]
done

**Comment by iemg** [comment]
Das ist auch eine Methode :smiley:  Danke!
