### ISSUE TITLE
Block 5 HÜ

### ISSUE THREAD

**Issue by iemg** [tuwien-geoweb/g07-2014#4]
Aufgabe:
Draw a marker at the most recent user or search result location. Add a button to re-center the map on the user's location. Instead of just centering the map on the new location, fit the map's extent to the accuracy circle of the Geolocation and the bounding box of the search result. 

Bonus:
- Vorsortierung: Einschränken der Suche auf Ö

**Comment by iemg** [comment]
Bonus:
- Style für Marker
- Suchformular schöner machen (bootstrap)

**Comment by iemg** [comment]
Einschränkung auf Ö: done
Marker at search result: done
accuracy circle of geolocation: daran verzweifelt
bounding box of search result: müsste schon so sein?!

**Comment by root676** [comment]
All issues fixed. All features implemented. Release is following...
