### ISSUE TITLE
Popover erscheint nicht. 

### ISSUE THREAD

**Issue by root676** [tuwien-geoweb/g07-2014#41]
Hallo @ahocevar !
Wir haben nach Fertigstellung des Projektes die Applikation aus Github auf den Student Webspace hochgeladen und eingebettet. Daraus ergibt sich jedoch folgendes Problem, welches wir nicht nachvollziehen können: Beim Click auf die Karte erscheint kein Popup mehr (in Github funktioniert es: http://tuwien-geoweb.github.io/g07-2014/wohnstandortanalyse/map.html ). Die Javascript Console gibt mir einen Fehler auf Codezeile 192 aus. Woran könnte die eingeschränkte Funktionstüchtigkeit liegen - die Konsolenmeldung bringt uns auf keinen grünen Zweig. Vielen Dank im Voraus!

http://student.ifip.tuwien.ac.at/geoweb/2014/g07/homepage/content/wohnstandortanalyse.php 

lg @root676

**Comment by iemg** [comment]
Ok, das war mein Pfusch, jquery.js war mit zwei unterschiedlichen Versionen eingebunden. Sry!

**Comment by e1025108** [comment]
Pfusch, pfusch, pfusch! :grin:
